markdown: rdiscount
pygments: true
auto: true
permalink: /:year/:month/:day/:title

host: neilzhang.yoyofind.com
name: "puresteel Zhang Blog"
disqus_shortname: "puresteel Zhang"
google_analytics: "UA-"
